### ISSUE TITLE
Please add CVE column to https://python-security.readthedocs.io/vulnerabilities.html

### ISSUE THREAD

**Issue by fdavis99** [vstinner/python-security#23]
Would be helpful if CVEs were displayed on top-level list.

Beautiful project!

**Comment by vstinner** [comment]
Done in commit 3bae8a7fc5dc9f2918b90a48ff81e98147767607. It should be online soon.

The problem is that the theme used by https://python-security.readthedocs.io/vulnerabilities.html doesn't leave much space for an additional column. Either the table should be rendered differently, or the theme should be modified, or another theme should be used. In the meanwhile, you may be able to scroll horizontally to see the CVE column.
